import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

// Report class representing reports generated by career center staff
public class Report {
    private String reportID;
    private String reportData;
    private Date generatedDate;
    private String reportType; // Added based on common report requirements
    private CareerCenterStaff generatedBy; // Staff who generated the report
    private Map<String, Object> filters; // Filter criteria used for this report

    // constructor with filters
    public Report(String reportID, String reportData, CareerCenterStaff generatedBy,
            String reportType, Map<String, Object> filters) {
        this.reportID = reportID;
        this.reportData = reportData;
        this.generatedDate = new Date();
        this.generatedBy = generatedBy;
        this.reportType = reportType;
        this.filters = (filters != null) ? new HashMap<>(filters) : new HashMap<>();
    }

    // constructor without filters
    public Report() {
        this.reportID = generateReportID();
        this.generatedDate = new Date();
        this.reportData = "";
        this.reportType = "General";
        this.filters = new HashMap<>();
    }

    // getters and setters
    public String getReportID() {
        return reportID;
    }

    public void setReportID(String reportID) {
        this.reportID = reportID;
    }

    public String getReportData() {
        return reportData;
    }

    public void setReportData(String reportData) {
        this.reportData = reportData;
    }

    public Date getGeneratedDate() {
        return generatedDate;
    }

    public void setGeneratedDate(Date generatedDate) {
        this.generatedDate = generatedDate;
    }

    public String getReportType() {
        return reportType;
    }

    public void setReportType(String reportType) {
        this.reportType = reportType;
    }

    public CareerCenterStaff getGeneratedBy() {
        return generatedBy;
    }

    public void setGeneratedBy(CareerCenterStaff generatedBy) {
        this.generatedBy = generatedBy;
    }

    public Map<String, Object> getFilters() {
        return new HashMap<>(filters); // Return copy to preserve encapsulation
    }

    public void setFilters(Map<String, Object> filters) {
        this.filters = (filters != null) ? new HashMap<>(filters) : new HashMap<>();
    }

    // add a filter criteria
    public void addFilter(String key, Object value) {
        filters.put(key, value);
    }

    // remove a filter criteria
    public void removeFilter(String key) {
        filters.remove(key);
    }

    // get a specific filter value
    public Object getFilter(String key) {
        return filters.get(key);
    }

    // check if a specific filter exists
    public boolean hasFilter(String key) {
        return filters.containsKey(key);
    }

    // check if any filters are applied
    public boolean hasActiveFilters() {
        return !filters.isEmpty();
    }

    // clear filters
    public void clearFilters() {
        filters.clear();
    }

    // display report summary including filters
    public void displayReportSummary() {
        System.out.println("=== Report Summary ===");
        System.out.println("Report ID: " + reportID);
        System.out.println("Type: " + reportType);
        System.out.println("Generated Date: " + generatedDate);
        System.out.println("Generated By: " + (generatedBy != null ? generatedBy.getName() : "Unknown"));
        System.out.println("Active Filters: " + (hasActiveFilters() ? filters.size() : "None"));

        if (hasActiveFilters()) {
            System.out.println("Filter Details:");
            for (Map.Entry<String, Object> entry : filters.entrySet()) {
                System.out.println("  • " + entry.getKey() + ": " + entry.getValue());
            }
        }

        System.out.println("Data Length: " + reportData.length() + " characters");
        System.out.println("======================");
    }

    // export report to text file
    public void exportToFile(String filename) {
        // ensure filename has .txt extension
        if (!filename.toLowerCase().endsWith(".txt")) {
            filename += ".txt";
        }

        try (PrintWriter writer = new PrintWriter(new FileWriter(filename))) {
            // write report header
            writer.println("=== INTERNSHIP PLACEMENT MANAGEMENT SYSTEM REPORT ===");
            writer.println();

            // write report metadata
            writer.println("Report ID: " + reportID);
            writer.println("Report Type: " + reportType);
            writer.println("Generated Date: " + generatedDate);
            writer.println("Generated By: " + (generatedBy != null ? generatedBy.getName() : "Unknown"));
            writer.println();

            // write filter information
            writer.println("=== FILTER CRITERIA ===");
            if (hasActiveFilters()) {
                for (Map.Entry<String, Object> entry : filters.entrySet()) {
                    writer.println(entry.getKey() + ": " + entry.getValue());
                }
            } else {
                writer.println("No active filters");
            }
            writer.println();

            // write report data
            writer.println("=== REPORT DATA ===");
            writer.println(reportData);
            writer.println();

            // write footer
            writer.println("=== END OF REPORT ===");
            writer.println("Total characters: " + reportData.length());
            writer.println("Export timestamp: " + new Date());

            System.out.println("Successfully exported report '" + reportID + "' to file: " + filename);

        } catch (IOException e) {
            System.err.println("Error exporting report to file: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // generate a unique report ID
    private String generateReportID() {
        return "RPT" + System.currentTimeMillis();
    }

    // toString method for displaying report information
    @Override
    public String toString() {
        return "Report{" +
                "reportID='" + reportID + '\'' +
                ", reportType='" + reportType + '\'' +
                ", generatedDate=" + generatedDate +
                ", filters=" + filters.size() +
                ", dataLength=" + reportData.length() +
                '}';
    }
}